CREATE DATABASE TeaDB;

CREATE TABLE TeaDB.Prices (
Id INTEGER NOT NULL auto_increment,
Price FLOAT(15) NOT NULL,
PRIMARY KEY (Id)
) ENGINE = MyISAM;

CREATE TABLE TeaDB.Shops (
Id INTEGER NOT NULL auto_increment,
Name VARCHAR(80) NOT NULL,
Location VARCHAR(80) NOT NULL,
Homepage VARCHAR(150),
Email VARCHAR(150),
PRIMARY KEY (Id)
) ENGINE = MyISAM;

CREATE TABLE TeaDB.Tea_registrations (
Id INTEGER NOT NULL auto_increment,
TeaId INTEGER NOT NULL,
ShopId INTEGER NOT NULL,
PriceId INTEGER NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (TeaId) REFERENCES Tea_types(Id),
FOREIGN KEY (ShopId) REFERENCES Shops(Id),
FOREIGN KEY (PriceId) REFERENCES Prices(Id)
) ENGINE = MyISAM;

CREATE TABLE TeaDB.Tea_types (
Id INTEGER NOT NULL auto_increment,
Name VARCHAR(150) NOT NULL,
Type VARCHAR(150) NOT NULL,
Country VARCHAR(100) NOT NULL,
Territory VARCHAR(100),
Year INTEGER(4) NOT NULL,
Description VARCHAR(1000),
PRIMARY KEY (Id)
) ENGINE = MyISAM;