CREATE TABLE TeaDB.Tea_registrations (
Id INTEGER NOT NULL auto_increment,
TeaId INTEGER NOT NULL,
ShopId INTEGER NOT NULL,
PriceId INTEGER NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (TeaId) REFERENCES Tea_types(Id),
FOREIGN KEY (ShopId) REFERENCES Shops(Id),
FOREIGN KEY (PriceId) REFERENCES Prices(Id)
) ENGINE = MyISAM;